services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    huh.google_maps.command.migrate_dlh:
        class: HeimrichHannot\GoogleMapsBundle\Command\MigrateDlhCommand