services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'

    HeimrichHannot\GoogleMapsBundle\Command\MigrateDlhCommand: ~