services:
  huh.google_maps.map_manager:
    class: HeimrichHannot\GoogleMapsBundle\Manager\MapManager
    public: true
    shared: false
    arguments:
      - "@contao.framework"
      - "@huh.google_maps.overlay_manager"
      - "@huh.utils.model"
      - "@huh.utils.location"
      - "@huh.utils.file"
      - "@twig"
  huh.google_maps.overlay_manager:
    class: HeimrichHannot\GoogleMapsBundle\Manager\OverlayManager
    public: true
    shared: false
    arguments:
      - "@contao.framework"
      - "@huh.utils.model"
      - "@huh.utils.location"
      - "@huh.utils.file"
      - "@twig"