services:
  _defaults:
    autoconfigure: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
  huh.google_maps.twig.extension:
    class: HeimrichHannot\GoogleMapsBundle\Twig\Extension
    tags:
      - { name: twig.extension }
    arguments:
    - "@huh.google_maps.map_manager"